apiVersion: v1
kind: Service
metadata:
  name: {{ include "flarum.fullname" . }}
  labels:
    {{- include "flarum.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "flarum.commonAnnotations" . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "flarum.selectorLabels" . | nindent 4 }}
